### ISSUE TITLE
Show nicer names for Players (not filesnames)

### ISSUE THREAD

**Issue by supernovatabletop** [supernovatabletop/supernova#7]
Show "Tempest of Fury" or "Dominik 'Tempest of Fury'" instead of the filename "tempest" on the rankings and pairings pages.

**Comment by PascalHann** [comment]
i am looking into that, but it poses a challenge to link to the player page data to the pairing page data

**Comment by PascalHann** [comment]
New player attribute 'displayname' was introduced. This attribute will be used in rankings and pairings.
