### ISSUE TITLE
Mark inactive Players

### ISSUE THREAD

**Issue by supernovatabletop** [supernovatabletop/supernova#8]
mark (grey out e.g.) all player in the player overview when they aren't participating in the highest phase

**Comment by PascalHann** [comment]
I could make it so that inactive players do not have a link to their page in the player overview. So you see them but you cant click on them to get to their page. I could add "inactive" to their name in addition. Is that what you want?

**Comment by PascalHann** [comment]
Incative players(players who do not participate in the current phase) are greyed out in player overview and marked with "(inactive)" in addition
